
const Actions = {
	SET_SELECTED_PRICE: 'SET_SELECTED_PRICE',
	SET_SELECTED_PRICE_NA: 'SET_SELECTED_PRICE_NA',

	SET_SELECTED_ROW: 'SET_SELECTED_ROW',
	SET_SELECTED_ROW_NA: 'SET_SELECTED_ROW_NA'
};

export default Actions;